// Generated by CoffeeScript 1.6.3
(function() {
  var analyse, constants, eventBroker, initialise, pubsub;

  constants = require('./constants');

  pubsub = require('pub-sub');

  eventBroker = pubsub.getEventBroker(constants.names.eventBroker);

  initialise = function() {
    return eventBroker.subscribe({
      name: constants.events.analyseSource,
      callback: analyse
    });
  };

  analyse = function(event) {
    var xhr;
    xhr = new XMLHttpRequest();
    return xhr.onreadystatechange = function() {};
  };

  module.exports = {
    initialise: initialise
  };

}).call(this);
