// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  module.exports = {
    ids: {
      form: 'source-form'
    },
    names: {
      eventBroker: 'jscomplexity'
    },
    events: {
      submit: 'submit',
      analyseSource: 'analyse-source'
    }
  };

}).call(this);
