// Generated by CoffeeScript 1.6.3
(function() {
  var constants, initialise, pubsub, serialiseForm;

  constants = require('./constants');

  pubsub = require('pub-sub');

  initialise = function(element) {
    var eventBroker;
    eventBroker = pubsub.getEventBroker(constants.names.eventBroker);
    return element.addEventListener(constants.events.submit, function(event) {
      eventBroker.publish(pubsub.createEvent({
        name: constants.events.analyseSource,
        data: serialiseForm(element)
      }));
      return event.preventDefault();
    });
  };

  serialiseForm = function(element) {
    var input, inputs, result, _i, _len;
    result = {};
    inputs = element.getElementsByTagName('input');
    for (_i = 0, _len = inputs.length; _i < _len; _i++) {
      input = inputs[_i];
      result[input.getAttribute('name')] = input.value;
    }
    return result;
  };

  module.exports = {
    initialise: initialise
  };

}).call(this);
